## TOML Uranio

db = "mongo"
encryption_rounds = 12
max_password_length = 58
storage = 'aws'
connect_on_init = true
[log]
	debug_info = false
	color = false
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[dev.log]
	debug_info = false
	color = true
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[client.log]
	debug_info = false
	color = false
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[client.dev.log]
	debug_info = false
	color = false
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
